### ISSUE TITLE
Install instructions are broken

### ISSUE THREAD

**Issue by anijain2305** [mila-iqia/myia#388]
Hi, it seems that the installation instructions are not up to date

https://github.com/mila-iqia/myia/blob/master/ALPHA.md

There are no requirements file. Please let me know if I am missing anything.

**Comment by strint** [comment]
@anijain2305 
You can refer to https://github.com/mila-iqia/myia/blob/master/scripts/ci-install.sh，user Python Poetry to install Myia. This way works for me.
