### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by breuleux** [mila-iqia/myia#43]
We all agree that Myia should support broadcasting. By broadcasting, I mean the feature wherein element-wise operations on multiple arguments automatically replicate each argument along their unitary dimensions until every argument has the same shape. So e.g. adding a row vector to a matrix adds the row vector to every row of the matrix.

The question is how this should be integrated. I can see three options:

1. Fold broadcasting into the `map` primitive (which is also pending).
2. Add a `broadcast` primitive. Python builtins would refer to graphs that compose `map` and `broadcast`.
3. Same as 2, but using a different primitive.

The issue with 1 is that it complicates the primitive quite a bit, as well as the gradient, since backpropagating through a broadcast involves a sum over broadcasted axes. I would rather not do it like that.

Regarding 2, assuming that `x2, y2 = broadcast(x, y)` returns x2 and y2 such that x2 and y2 have the same shape and are at least as large as both x and y, I suppose the bprop would be something like:

```python
def bprop_broadcast(x, y, dout):
    dx2, dy2 = dout
    ax, ay = broadcast_axes(x, y)
    dx = sum(dx2, axes=ax)
    dy = sum(dy2, axes=ay)
    return dx, dy
```

So we would need to add a `broadcast_axes` primitive to get summation axes to give to `sum`.

One alternative that I played with in master would be the `fit` primitive, which would subsume both `sum` and `broadcast`. `fit(x, shape)` would broadcast any unitary dimension of `x` to the size given in `shape`, and sum over any unitary dimension in `shape`. So a broadcastable operation like `add` would become:

```python
def add(x, y):
    shp = map(max, shape(x), shape(y))
    return map(scalar_add, fit(x, shp), fit(y, shp))
```

As for the gradient, it's pretty simple:

```python
def bprop_fit(x, shp, dout):
    return fit(dout, shape(x)), zeros_like(shp)
```

`fit` isn't particularly simple as a primitive, but not in an unintuitive way in my opinion, and it can do both `broadcast` and `sum`. Also, I like the fact the bprop of `fit` is another `fit`.

Another possibility would be individual-axis functions like `repeat(arr, axis, n)` and `sum(arr, axis)`, but I think they'll be tedious to compose.

Thoughts?

**Comment by obilaniu** [comment]
@breuleux I very much like the idea of the `fit()` primitive because of this self-duality.

We already need to handle broadcasting of gradients backwards for `sum()`, and are here considering our need for `broadcast()`. If we are ready to do both, then we are also ready to instead do a `fit()` primitive. To borrow a modified Einsum-like notation, the symmetries become quite obvious:

```python
B    = fit("ijkl->jk", A)    # 4D-to-2D pure 2D summation over il
dLdA = fit("jk->ijkl", dLdB) # 2D-to-4D pure 2D broadcast to il

B    = fit("ijk->jmk", A)    # 3D-to-3D mixed op: 1D summation over i, then broadcast to m
dLdA = fit("jmk->ijk", dLdB) # 3D-to-3D mixed op: 1D summation over m, then broadcast to i
...
```

The fact that the only thing that changes is the order of the "specs" is truly elegant.

**Comment by lamblin** [comment]
I would be strongly in favour of having both `sum` (maybe implemented as `map(add, ...)`), and `repeat`, things that we would need elsewhere anyway, instead of an *ad hoc* `fit` primitive.

**Comment by bartvm** [comment]
Echoing @lamblin, I think we should find an actual primitive i.e. something that is fully general and not a composition of multiple operations.

In NumPy, the most primitive operation is arguably [`as_strided`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.lib.stride_tricks.as_strided.html), and I think we should adopt a similar primitive i.e. given tensor `x`, return a tensor `y` that has a given shape and strides. If we add an `offset` argument, then this one primitive would allow us to do slicing, indexing, broadcasting, and more complicated stuff (for example, constructing Toeplitz-like matrices for n-grams given a vector sequence).

For broadcasting, you could introduce a second primitive, `broadcast(x, y) -> expanded_shape, x_strides, y_strides`, that can then be used to expand the matrices before applying a binary operation on them. So `z = x + y` maps to `s, x_s, y_s = broadcast(x, y); x_ = as_strided(x, s, x_s); y_ = as_strided(y, s, y_s); z = map(add, x_, y_)`.

Note that this older discussion is quite relevant: https://github.com/mila-udem/myia-private/issues/14

**Comment by breuleux** [comment]
I'm open to many options, I just want to make sure that the primitives' adjoints are reasonably simple. `as_strided` can create pretty crazy aliasing patterns, so I imagine the corresponding `sum` you would have to do for the gradient would have to be correspondingly crazy. I haven't thought a lot about it, though, it may be simpler than my first impression.

Another possibility is to have `fold` and `unfold` primitives (broadcasting is a special case of `unfold`), which are dual I think (`unfold` can also do `range`, `zeros`, etc). Although `unfold` wouldn't alias, so we might need to replace compatible uses with a `repeat` primitive to save memory.

Also, it's not entirely clear to me what `reduce` should be. Traditionally there is `foldl` and `foldr` which implement left-associative and right-associative reduction respectively, but e.g. for `sum` which is associative, we would rather just do it in parallel (`foldp`?) Might be a bit tricky.

**Comment by breuleux** [comment]
This has been working for a while.
